# Generated by Django 6.1.1 on 2026-09-18 09:02

import diagramas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('diagram_type', models.CharField(choices=[('CLASS', 'Diagrama de Clases UML 2.5')], default='CLASS', max_length=50)),
                ('version', models.PositiveIntegerField(default=1, help_text='Control de versión incremental para concurrencia')),
                ('semantic_data', models.JSONField(blank=True, default=diagramas.models.default_semantic_data)),
                ('visual_data', models.JSONField(blank=True, default=diagramas.models.default_visual_data)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diagrams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='proyectos.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
