# Generated by Django 6.1.1 on 2026-09-16 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW_PROJECT', 'Ver proyecto'), ('EDIT_PROJECT', 'Editar proyecto'), ('VIEW_MODEL', 'Ver modelo'), ('EDIT_MODEL', 'Editar modelo'), ('USE_AI', 'Usar IA'), ('VALIDATE_MODEL', 'Validar modelo'), ('GENERATE_BACKEND', 'Generar backend'), ('IMPORT_MODEL', 'Importar modelo'), ('EXPORT_MODEL', 'Exportar modelo'), ('MANAGE_MEMBERS', 'Gestionar miembros'), ('MANAGE_ROLES', 'Gestionar roles'), ('VIEW_HISTORY', 'Ver historial')], max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
